[2024-04-12T06:17:09.717] [TRACE] enrollment - vendor-enrollment-createenrollment - undefined - error in insert query
[2024-04-12T06:17:09.717] [ERROR] enrollment - Error: Unknown column 'toalTime' in 'field list'
    at Packet.asError (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'toalTime' in 'field list'",
  sql: 'INSERT INTO `enrollments` (`subType`,`cost`,`toalTime`,`isRenewal`,`userId`,`type`) VALUES (NULL,NULL,NULL,NULL,NULL,NULL);'
}
[2024-04-12T06:17:09.719] [TRACE] enrollment - vendor-enrollment-createenrollment - undefined - error thrown
[2024-04-12T06:17:09.719] [ERROR] enrollment - {
  status: 'failed',
  err: Error: Unknown column 'toalTime' in 'field list'
      at Packet.asError (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'toalTime' in 'field list'",
    sql: 'INSERT INTO `enrollments` (`subType`,`cost`,`toalTime`,`isRenewal`,`userId`,`type`) VALUES (NULL,NULL,NULL,NULL,NULL,NULL);'
  },
  data: { bResult: false }
}
[2024-04-12T06:19:03.835] [TRACE] enrollment - vendor-enrollment-createenrollment - undefined - error in insert query
[2024-04-12T06:19:03.835] [ERROR] enrollment - Error: Unknown column 'toalTime' in 'field list'
    at Packet.asError (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'toalTime' in 'field list'",
  sql: 'INSERT INTO `enrollments` (`subType`,`cost`,`toalTime`,`isRenewal`,`userId`,`type`) VALUES (NULL,NULL,NULL,NULL,NULL,NULL);'
}
[2024-04-12T06:19:03.836] [TRACE] enrollment - vendor-enrollment-createenrollment - undefined - error thrown
[2024-04-12T06:19:03.836] [ERROR] enrollment - {
  status: 'failed',
  err: Error: Unknown column 'toalTime' in 'field list'
      at Packet.asError (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'toalTime' in 'field list'",
    sql: 'INSERT INTO `enrollments` (`subType`,`cost`,`toalTime`,`isRenewal`,`userId`,`type`) VALUES (NULL,NULL,NULL,NULL,NULL,NULL);'
  },
  data: { bResult: false }
}
[2024-04-12T06:19:22.052] [TRACE] enrollment - vendor-enrollment-createenrollment - 8 - error in insert query
[2024-04-12T06:19:22.052] [ERROR] enrollment - Error: Unknown column 'toalTime' in 'field list'
    at Packet.asError (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'toalTime' in 'field list'",
  sql: "INSERT INTO `enrollments` (`subType`,`cost`,`toalTime`,`isRenewal`,`userId`,`type`) VALUES ('Driving License','1000',NULL,'false','8','LMV');"
}
[2024-04-12T06:19:22.053] [TRACE] enrollment - vendor-enrollment-createenrollment - 8 - error thrown
[2024-04-12T06:19:22.053] [ERROR] enrollment - {
  status: 'failed',
  err: Error: Unknown column 'toalTime' in 'field list'
      at Packet.asError (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'toalTime' in 'field list'",
    sql: "INSERT INTO `enrollments` (`subType`,`cost`,`toalTime`,`isRenewal`,`userId`,`type`) VALUES ('Driving License','1000',NULL,'false','8','LMV');"
  },
  data: { bResult: false }
}
[2024-04-12T06:20:26.727] [TRACE] enrollment - vendor-enrollment-createenrollment - 8 - error in insert query
[2024-04-12T06:20:26.727] [ERROR] enrollment - Error: Unknown column 'userId' in 'field list'
    at Packet.asError (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 'userId' in 'field list'",
  sql: "INSERT INTO `enrollments` (`subType`,`cost`,`totalTime`,`isRenewal`,`userId`,`type`) VALUES ('Driving License','1000',NULL,'false','8','LMV');"
}
[2024-04-12T06:20:26.728] [TRACE] enrollment - vendor-enrollment-createenrollment - 8 - error thrown
[2024-04-12T06:20:26.728] [ERROR] enrollment - {
  status: 'failed',
  err: Error: Unknown column 'userId' in 'field list'
      at Packet.asError (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'userId' in 'field list'",
    sql: "INSERT INTO `enrollments` (`subType`,`cost`,`totalTime`,`isRenewal`,`userId`,`type`) VALUES ('Driving License','1000',NULL,'false','8','LMV');"
  },
  data: { bResult: false }
}
[2024-04-12T06:20:45.531] [TRACE] enrollment - vendor-enrollment-createenrollment - 8 - error in insert query
[2024-04-12T06:20:45.532] [ERROR] enrollment - Error: Cannot add or update a child row: a foreign key constraint fails (`mayur_db`.`enrollments`, CONSTRAINT `fk_user_profile_for_enrollment` FOREIGN KEY (`User_profile_ID`) REFERENCES `user_profile` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)
    at Packet.asError (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:456:32)
    at PacketParser.onPacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:85:12)
    at PacketParser.executeStart (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:92:25)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5) {
  code: 'ER_NO_REFERENCED_ROW_2',
  errno: 1452,
  sqlState: '23000',
  sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`mayur_db`.`enrollments`, CONSTRAINT `fk_user_profile_for_enrollment` FOREIGN KEY (`User_profile_ID`) REFERENCES `user_profile` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)',
  sql: "INSERT INTO `enrollments` (`subType`,`cost`,`totalTime`,`isRenewal`,`User_profile_ID`,`type`) VALUES ('Driving License','1000',NULL,'false','8','LMV');"
}
[2024-04-12T06:20:45.533] [TRACE] enrollment - vendor-enrollment-createenrollment - 8 - error thrown
[2024-04-12T06:20:45.533] [ERROR] enrollment - {
  status: 'failed',
  err: Error: Cannot add or update a child row: a foreign key constraint fails (`mayur_db`.`enrollments`, CONSTRAINT `fk_user_profile_for_enrollment` FOREIGN KEY (`User_profile_ID`) REFERENCES `user_profile` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)
      at Packet.asError (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packets/packet.js:728:17)
      at Query.execute (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/commands/command.js:29:26)
      at PoolConnection.handlePacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:456:32)
      at PacketParser.onPacket (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:85:12)
      at PacketParser.executeStart (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/Users/yash/Documents/Mayur Motors/Server/node_modules/mysql2/lib/connection.js:92:25)
      at Socket.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
      at Readable.push (node:internal/streams/readable:390:5) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlState: '23000',
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`mayur_db`.`enrollments`, CONSTRAINT `fk_user_profile_for_enrollment` FOREIGN KEY (`User_profile_ID`) REFERENCES `user_profile` (`ID`) ON DELETE NO ACTION ON UPDATE CASCADE)',
    sql: "INSERT INTO `enrollments` (`subType`,`cost`,`totalTime`,`isRenewal`,`User_profile_ID`,`type`) VALUES ('Driving License','1000',NULL,'false','8','LMV');"
  },
  data: { bResult: false }
}
[2024-04-12T04:01:40.096] [TRACE] enrollment - vendor-enrollment-fetchusercertifications - 8 - error in db connection
[2024-04-12T04:01:40.096] [ERROR] enrollment - Error: connect ETIMEDOUT
    at PoolConnection._handleTimeoutError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:189:17)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  fatal: true
}
[2024-04-12T04:01:40.097] [TRACE] enrollment - vendor-enrollment-fetchusercertifications - 8 - error thrown
[2024-04-12T04:01:40.097] [ERROR] enrollment - {
  status: 'failed',
  err: Error: connect ETIMEDOUT
      at PoolConnection._handleTimeoutError (/workspaces/MAYUR-SERVER/Server/node_modules/mysql2/lib/connection.js:189:17)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  },
  data: { bResult: false }
}
